var chainsmokers_songs = [
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "New york city",
    song: "http://docs.google.com/uc?export=open&id=16pDWpPKvmW7y8rIlaanzDogdlSfMfY-w",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Paris",
    song: "http://docs.google.com/uc?export=open&id=1LzowRvH-sc_Q1UbXaSwtDVVVkFAzNvDV",
    color: "false",
  },

  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Girlfriend",
    song: "http://docs.google.com/uc?export=open&id=1NzMxV2sy8ouj0KOmybl1hlkRUoWNob4s",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Don't let me down",
    song: "http://docs.google.com/uc?export=open&id=1PQ7IhlAiDnyjwBChI5zH0QTvJab9ncrW",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Selfie",
    song: "http://docs.google.com/uc?export=open&id=1QOHZQSbhSuFJh-s_sCvVt5zsquDlw2aU",
    color: "false",
  },

  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Inside out",
    song: "http://docs.google.com/uc?export=open&id=1VSMqWZay3HZE7OYlIXDMQAVe96bsVUNx",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Water bed",
    song: "http://docs.google.com/uc?export=open&id=1Ww15U00PKh48i_jTzKXXWASqtH5b0U5L",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Roses",
    song: "http://docs.google.com/uc?export=open&id=1fnWcxaLn_iV-QTN9QTTQt1MPpJ-H4A3z",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Let you go",
    song: "http://docs.google.com/uc?export=open&id=1h45lNRf4UEvTsaJxPdPlIQvY4PaENUtD",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "All we know",
    song: "http://docs.google.com/uc?export=open&id=1lGdRzulAY_vSiSBC9O_1NVjQX663dZUg",
    color: "false",
  },

  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Closer",
    song: "http://docs.google.com/uc?export=open&id=1puDgMg6NtU6UXY7i_K1HetVy6KOOEqza",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "Kenye",
    song: "http://docs.google.com/uc?export=open&id=1vclLv-GdhVYqkQ3yktAu9RRXk68UlQrh",
    color: "false",
  },
  {
    img: "https://www.maxim.com/.image/t_share/MTczODUwMzcxOTQ3NTA1NTA1/the-chainsmokers.jpg",
    artistName: "ChainSmokers",
    songName: "The rookie",
    song: "http://docs.google.com/uc?export=open&id=1xvQcsBve2P1oCHI6r2cLY5WgC--TLVJB",
    color: "false",
  },
];

var coldplay_songs = [
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Viva La Vida",
    song: "http://docs.google.com/uc?export=open&id=1jzdsLuAwGPSucPjevoRoLGO17u5pJYhU",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "The Scientist",
    song: "http://docs.google.com/uc?export=open&id=1J41XcEELXo4oDwpMEYT4x9MSEIniRdN-",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "A Sky Full of Stars",
    song: "http://docs.google.com/uc?export=open&id=15TJvOHj5JHXmMAYKmUsG9P15snU2eRYs",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Paradise",
    song: "http://docs.google.com/uc?export=open&id=1dWxaTJhA32Sqy9xwhAUQZxg4qkTnX1zr",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Yellow",
    song: "http://docs.google.com/uc?export=open&id=12plEZxJm4GXFzkBSEi0eTkjREw-c0b-k",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Hymn For The Weekend",
    song: "http://docs.google.com/uc?export=open&id=1sDM1Ht6gSujIcNRz3Cmr-7jABsLhWIer",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Gravity",
    song: "http://docs.google.com/uc?export=open&id=1HupL3Aq0mgSyZX-lSnigPYumf6i0RXi1",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "O",
    song: "http://docs.google.com/uc?export=open&id=1K7rtylYOjRr5QmBqy169Saqdhg9JukmU",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Everglow",
    song: "http://docs.google.com/uc?export=open&id=1bP-tNkLnVCewijt7nr8gfAuZeqnP7Jzh",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Fix You",
    song: "https://docs.google.com/uc?export=open&id=1bk0x9SjcOmeO9gzKLbWYjcUeU9KJ5HfW",
    color: "false",
  },
  {
    img: "https://yt3.ggpht.com/ytc/AAUvwniJQKE6BirVS0nIpVjL3X_-ZRmWfK5cZiQ2BqHc3A=s900-c-k-c0x00ffffff-no-rj",
    artistName: "ColdPlay",
    songName: "Talk",
    song: "http://docs.google.com/uc?export=open&id=1DV-VGW7zamYoGpA2ll_hrg7NWPkNY-XT",
    color: "false",
  },
];
